id: P004225
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:02:46.906862
source_metadata:
  id: bdr:W8LS17565
  title: སུ་མ་ཏི་དྷྭ་ཛ་སིདྷིའི་རྟོགས་བརྗོད།
  author: ''
  volumes:
    86b58004b3364d3295fb0bef677b0246:
      image_group_id: I8LS17572
      title: ''
      volume_number: 1
      total_pages: 654
      base_file: v001.txt
    5e95bbd6122945b29761bfae72fcd3f5:
      image_group_id: I8LS17573
      title: ''
      volume_number: 2
      total_pages: 2
      base_file: v002.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
